### ISSUE TITLE
Change password error message is not clear

### ISSUE THREAD

**Issue by at-thangtc** [AsianTechInc/AT-Portal#1]
I changed the password for the first time login and got a message like "Password is invalid".
This is a general message, I don't know what is the reason. So please the message that show more meaning, like the password must have at least one special character or something like that.

I hope your team improve this message.
Thanks a lot!

**Comment by at-huett** [comment]
I think this is not bug.
We had clear note for Password format at Input form.
You can consult image enclosed
![8](https://cloud.githubusercontent.com/assets/13691743/20340185/f6f95be4-ac12-11e6-86fa-e7566ced0072.png)

Thank for contributing your ideas!
ATP team.

**Comment by at-thangtc** [comment]
@at-huett 
Oh, thank you !
