### ISSUE TITLE
[Com_Leave] No dialog confirm when switch from leave to home

### ISSUE THREAD

**Issue by at-nhantt** [AsianTechInc/AT-Portal#10]
I create new request leave and input content.
I try to switch to Home and no dialog confirm that my inputted content is deleted. 
But,... switching is very fast. That's very well. (devil)
Then, I back to my leave and nothing is saved. 

I think it's basic bug. I hope u fix it. 

Thanks!

**Comment by at-datnm** [comment]
@at-nhantt 

-We still have not implement this function yet but we will discussion about this issue

Thanks for your contribution
ATP-Team

**Comment by at-huydq** [comment]
@at-nhantt This is not a bug, you deliberately clicked Home. Do you suggest to have form content saved even going away from the form? we can discuss it as another matter.
