### ISSUE TITLE
Need to show project ID in Project list screen

### ISSUE THREAD

**Issue by at-toannt** [AsianTechInc/AT-Portal#17]
Project ID is needed for cross reference among different reports from Sales to FIN.

**Comment by at-datnm** [comment]
@at-toannt 
-This feature will be added in the future

Thank for your contribution
ATP-Team

**Comment by at-huett** [comment]
@at-toannt 
This is fixed and update in https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.5-beta.

Thank you!
