### ISSUE TITLE
[Leave of Others] No start date and end date

### ISSUE THREAD

**Issue by at-tienlp** [AsianTechInc/AT-Portal#18]
![screen shot 2016-11-17 at 8 45 05 am](https://cloud.githubusercontent.com/assets/16131955/20373128/9d8c1aac-aca2-11e6-98e0-7d3240722980.png)

I want to know information about the start date and end date of the application for leave.

**Comment by at-huydq** [comment]
@at-vinht @at-lamht @at-huett please action on this one. Small and easy but important.
