### ISSUE TITLE
[My timesheet] Display error msg when submitting timesheet

### ISSUE THREAD

**Issue by at-hantk** [AsianTechInc/AT-Portal#19]
After input all days and click submit, the error msg was displayed with content "Timesheet invalid, please check again!". The error msg must be clearly. At least, the wrong input becomes red to know.

**Comment by at-huett** [comment]
@at-hantk 
This bug is fixed and note on https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.4-beta.

Thanks so much.
