### ISSUE TITLE
Can't cancel wrong task in Timesheet

### ISSUE THREAD

**Issue by at-longhpv** [AsianTechInc/AT-Portal#2]
![screenshot from 2016-11-16 08 34 38](https://cloud.githubusercontent.com/assets/17695632/20331422/b7f5a5f0-abd7-11e6-816a-24847d182b95.png)
I registered the wrong task on Sunday. So i wanna cancel. But system wont let me delete. Change Only.
Is this a bug ?
Thanks you

**Comment by at-huett** [comment]
This is a bug.
We will fix it.

Thanks for sharing your opinions.
ATP-team.

**Comment by at-huett** [comment]
@at-longhpv 
This bug is fixed and note on #https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.4-beta

Thanks so much.
