### ISSUE TITLE
Submit timesheet

### ISSUE THREAD

**Issue by at-nhantv** [AsianTechInc/AT-Portal#22]
Users must fill none project before submit.
I think users do not need to do it.
![timesheet](https://cloud.githubusercontent.com/assets/19969406/20425412/0a720144-adad-11e6-8710-9087e4b0dec8.png)

**Comment by at-huett** [comment]
@at-nhantv 
This is a bug, we fixed it and deployed in Nov 19th 2016.
You can check it again. 

Thanks so much.
