### ISSUE TITLE
Get link

### ISSUE THREAD

**Issue by at-nhantv** [AsianTechInc/AT-Portal#23]
Users can access some pages by way get link.
Below is some images
![screen shot 2016-11-18 at 4 40 32 pm](https://cloud.githubusercontent.com/assets/19969406/20425730/6afc90aa-adae-11e6-911a-88ca330871a3.png)
![screen shot 2016-11-18 at 4 41 48 pm](https://cloud.githubusercontent.com/assets/19969406/20425732/6afeda68-adae-11e6-8c26-79d890134f81.png)
![screen shot 2016-11-18 at 4 42 09 pm](https://cloud.githubusercontent.com/assets/19969406/20425731/6afcadf6-adae-11e6-975d-b27b7fd0f80e.png)
![screen shot 2016-11-18 at 4 43 15 pm](https://cloud.githubusercontent.com/assets/19969406/20425733/6b0474d2-adae-11e6-9057-9dfeb83de5d6.png)

**Comment by at-huydq** [comment]
high priority bug, please raise this internally and close this bug.
