### ISSUE TITLE
[Project] Issue in "Create new project" screen

### ISSUE THREAD

**Issue by at-toannt** [AsianTechInc/AT-Portal#24]
#Position ==> Role
 - [x] Technical Leader ==> Team Leader 
 - [x] Add new resource, defaul start date should be "Today", end date should be "Project end date"
 - [x] Add more roles as “Game Designer”,  and “Game Artist”, Add role named “Other”

**Comment by at-datnm** [comment]
@at-toannt 
This is a bug. We will fix it

**Comment by at-datnm** [comment]
This bug is fixed. This issue is available in latest released
