### ISSUE TITLE
better content display for Leave request email

### ISSUE THREAD

**Issue by at-huydq** [AsianTechInc/AT-Portal#26]
current

> Team: FE
> 
> When:
> 
> - Thursday Dec 1st, 2016 Full Day
> - Friday Dec 2nd, 2016 Full Day
> - Monday Dec 5th, 2016 Full Day
> - Tuesday Dec 6th, 2016 Full Day
> Leave Type: Annual Leave
> 
> Message:
> 
> xxx
> xx
> xxx
> 

Need to become like this

> Team: FE
> Leave Type: Annual Leave
> When: 
>> 3 columns table start
> - Thursday Dec 1st, 2016 Full Day
> - Friday Dec 2nd, 2016 Full Day
> - Monday Dec 5th, 2016 Full Day
> - Tuesday Dec 6th, 2016 Full Day
>> table end
> Message: 
>> gray background start
> - xxx
> - xx
>> gray background end

**Comment by at-huett** [comment]
@at-huydq 
This issue is fixed and update in https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.5-beta

Thanks.
