### ISSUE TITLE
Timesheet rejected list become empty

### ISSUE THREAD

**Issue by at-huydq** [AsianTechInc/AT-Portal#27]
> When I reject timesheet, the list becomes blank, it does show the correct date-time. This is very annoying and take a long time for me to reject people. Should display a notification then refresh the list.

![screen shot 2016-11-21 at 11 02 02 am](https://cloud.githubusercontent.com/assets/16131698/20470332/364bd1a8-afda-11e6-81b2-88bc2c4a60ac.png)
![screen shot 2016-11-21 at 11 02 25 am](https://cloud.githubusercontent.com/assets/16131698/20470334/39b91f80-afda-11e6-9d72-f426ddef2b1c.png)
![screen shot 2016-11-21 at 11 02 35 am](https://cloud.githubusercontent.com/assets/16131698/20470338/3c985a22-afda-11e6-81ae-f585145cedc4.png)

**Comment by at-datnm** [comment]
This bug is fixed. This issue will be released in 0.2.2 beta and it's also updated in :
https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.2-beta
