### ISSUE TITLE
Button for Leave of Others should be renamed

### ISSUE THREAD

**Issue by at-huydq** [AsianTechInc/AT-Portal#28]
If I can approve that person, the button should be "Review"
If I have already approved/rejected, the button should be View Detail
If I can only view that person because I'm secondary Manager, then button should be "View Detail"
![screen shot 2016-11-21 at 11 07 50 am](https://cloud.githubusercontent.com/assets/16131698/20470470/8c6b4450-afdb-11e6-8c6b-8038695a6d6a.png)

**Comment by at-huett** [comment]
@at-huydq 
This bug is fixed and it's also updated in https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.4-beta

Thanks.
