### ISSUE TITLE
Critical: can not get past loading in SAFARI

### ISSUE THREAD

**Issue by at-huydq** [AsianTechInc/AT-Portal#31]
![screen shot 2016-11-21 at 11 49 35 am](https://cloud.githubusercontent.com/assets/16131698/20471047/b3833a84-afe0-11e6-9cfe-82da132c72a6.png)

**Comment by at-vinht** [comment]
**Solution**
We should refer this issue to handle this bug:
https://github.com/driftyco/ionic/issues/5721

**Comment by at-huydq** [comment]
as long as you can fix it. please
