### ISSUE TITLE
Can not approve Leave for this case on PROD

### ISSUE THREAD

**Issue by at-huydq** [AsianTechInc/AT-Portal#35]
{"meta":{"status":"failed","code":400,"message":"bad_request"},"data":{}}
2:27PM vietnam time

![screen shot 2016-11-21 at 2 13 06 pm](https://cloud.githubusercontent.com/assets/16131698/20473859/f784ad7a-aff5-11e6-9b62-b4a49117f118.png)
![screen shot 2016-11-21 at 2 22 27 pm](https://cloud.githubusercontent.com/assets/16131698/20473865/ffbf1444-aff5-11e6-9611-b0407c1f9a56.png)

**Comment by at-lamht** [comment]
@at-huydq 
Because he has only 2 days for annual leave

**Comment by at-huydq** [comment]
@at-lamht @at-vinht 
I know, but 400 error returned from server with no proper message is not acceptable. Should display clear message why it can't be accepted.

**Comment by at-huydq** [comment]
still a bug.

**Comment by at-lamht** [comment]
@at-huydq 
understand, i will fix it

**Comment by at-huett** [comment]
This bug is fixed. This issue will be released in version 0.2.2 beta and it's also updated in : https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.2-beta
