### ISSUE TITLE
Not show total entries

### ISSUE THREAD

**Issue by at-anhlt** [AsianTechInc/AT-Portal#4]
Lỗi FE bé bé thôi

<img width="476" alt="screen shot 2016-11-16 at 9 12 17 am" src="https://cloud.githubusercontent.com/assets/16131696/20332220/e6498fca-abdc-11e6-8086-ecc0d4735119.png">

Link : http://portal.asiantech.vn/module/project-management/program

**Comment by at-huett** [comment]
This is a bug
We will fix it.

Thank for contributing your opinion!
ATP-team.
