### ISSUE TITLE
List leave only display 10 items as maximum

### ISSUE THREAD

**Issue by at-dungnh** [AsianTechInc/AT-Portal#41]
I get list leave of other to approve or reject but it can display 10 items only, I think it's missing paginate on this list. Please check it.

**Comment by at-huydq** [comment]
@at-dungnh at the moment you can click con tab Pending.
@at-huett

**Comment by at-lamht** [comment]
@at-vinht BE updated API

**Comment by at-huett** [comment]
@at-dungnh 
This bug is fixed and it's also updated in : https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.4-beta

Thanks so much.
