### ISSUE TITLE
Need a comma "," between projects' name

### ISSUE THREAD

**Issue by at-huydq** [AsianTechInc/AT-Portal#42]
![screen shot 2016-11-22 at 1 59 58 pm](https://cloud.githubusercontent.com/assets/16131698/20513997/0a56705c-b0bc-11e6-8bdd-8bbdc5179a3d.png)

**Comment by at-huydq** [comment]
From

> Relax Sougou (Portal_2nd phase), Cardbook (2nd phase) 

Change to

> Relax Sougou (Portal_2nd phase), Cardbook (2nd phase)

**Comment by at-datnm** [comment]
This bug is fixed. It's available in latest released
