### ISSUE TITLE
Auto refresh does not work after I press approve/reject button on timesheet page

### ISSUE THREAD

**Issue by at-tienhn** [AsianTechInc/AT-Portal#43]
Step 1: Open timesheet > Timesheet or other
![screen shot 2016-11-22 at 5 25 09 pm](https://cloud.githubusercontent.com/assets/16132900/20520262/b62cc612-b0d8-11e6-8124-1f837efe143a.png)

Step 2: Click on reject button or approve button
Step 3: 
![screen shot 2016-11-22 at 5 26 39 pm](https://cloud.githubusercontent.com/assets/16132900/20520405/434c4f54-b0d9-11e6-81e8-6c71abed4f6c.png)

**Comment by at-huett** [comment]
@at-tienhn 
This is the same bug #27, so we will close it.

Thanks.

**Comment by at-huett** [comment]
This issue is released in 0.2.2 beta and it's also updated in :
https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.2-beta
