### ISSUE TITLE
Show wrong order of username!

### ISSUE THREAD

**Issue by at-trint** [AsianTechInc/AT-Portal#44]
At the beginning, the order of users like this:
```
1. Dai Ho V.
2. Ngoc Tran T.N.
3. Matsuo Takenobu
4. Lam Le V.
5. Tri Nguyen T.
```
Step1: Reject line 1 with user name "Dai Ho V."

The order of users will be changed like this:
```
1. Tri Nguyen T.
2. Ngoc Tran T.N.
3. Matsuo Takenobu
4. Lam Le V.
5. Dai Ho V.
```

And server sent mail to `Tri Nguyen T.`.

**Comment by at-huett** [comment]
@at-trint 
This is a high bug and we will fix early

Thanks so much.

**Comment by at-huett** [comment]
@at-trint 
I tested on many case but I can't reappear this issue.
So, we need image or video for this, you can help them?

Thanks so much.

**Comment by at-huydq** [comment]
Should we close this one? @at-huett @at-trint

**Comment by at-trint** [comment]
@at-huydq 
@at-huett 
This is a rare bug, I cannot reappear it neither.
So please close this, thank you!
