### ISSUE TITLE
[Leave of others] Member wasn't displayed in All tab

### ISSUE THREAD

**Issue by at-hantk** [AsianTechInc/AT-Portal#47]
Member(Quang Tran H.) wasn't displayed in All tab, but only displayed in Pending tab.
See attached image
![screen shot 2016-11-24 at 17 41 26](https://cloud.githubusercontent.com/assets/19488325/20595748/bf17dfc8-b26d-11e6-829b-222825657664.png)

**Comment by at-huett** [comment]
@at-hantk 
This is a bug,because currently at leave list don't handle for pagination.
And it is the same bug #41 so we will close it.

Thanks so much.

**Comment by at-huydq** [comment]
OK so I close this bug?
