### ISSUE TITLE
Content of the Leave notification is not correct

### ISSUE THREAD

**Issue by at-hieunt** [AsianTechInc/AT-Portal#48]
Please change texts in mail as following:
- Dear Hr.internal ==> Dear BO Team
- Project-member ==> (delete)
- Projects ==> Project(s) (or logical)
- Team ==> Team(s) (or logical)
![screen shot 2016-11-25 at 16 15 31](https://cloud.githubusercontent.com/assets/15623967/20620105/a516bf82-b32a-11e6-9865-c98a9b637658.png)

**Comment by at-huett** [comment]
@at-hieunt 
This issue is fixed and update in https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.5-beta

Thank you.
