### ISSUE TITLE
Have link to Group detail without view permission 

### ISSUE THREAD

**Issue by at-namlh** [AsianTechInc/AT-Portal#5]
Steps: 
1. Come to home screen
2. Click profile of user 
3. Click the name of manager, move to profile of manager
4. At Groups, click PMO
==> actual result: display error 403
![screen shot 2016-11-16 at 10 07 49 am](https://cloud.githubusercontent.com/assets/13046181/20333447/350cda1a-abe5-11e6-871e-248fb0ecc82e.png)

**Comment by at-huett** [comment]
This is a bug.
We will fix it.

Thank for contributing your opinion!
ATP-team.

**Comment by at-huydq** [comment]
This is a bug however it's due to the complexity around the Access Control code. We will fix it eventually in the future. As for now, it shouldn't be a problem.
