### ISSUE TITLE
Can't delete Other Activities 

### ISSUE THREAD

**Issue by at-kietva** [AsianTechInc/AT-Portal#51]
When I moving to TimeSheet page and fill sheet, I can't delete Other Activities
Bellow is how to check that issue : 
1. Move to my TimeSheet page
2. Tap to `Fill timesheet automatically`
3. No way can delete `Other Activities` in Non Project row.

**Comment by at-datnm** [comment]
Currently, user don't have permission to remove task when chossing "Fill timesheet automatically". This issue will be fixed in the future

**Comment by at-huett** [comment]
@at-kietva 
This bug is fixed and you can refer to #https://github.com/AsianTechInc/AT-Portal/wiki/Releases-Notes-0.2.4-beta


Thanks so much.
