### ISSUE TITLE
Have link to Team detail without view permission

### ISSUE THREAD

**Issue by at-namlh** [AsianTechInc/AT-Portal#6]
Steps:

1. Come to home screen
2. Click profile of user
3. At profile of user, click Teams QC
==> actual result: display error 403
![screen shot 2016-11-16 at 10 07 49 am](https://cloud.githubusercontent.com/assets/13046181/20333685/c7608366-abe6-11e6-846e-558569048a74.png)

**Comment by at-huett** [comment]
@at-namlh 
This bug is the same #5 
We will fix it.

Thank for contributing your opinions!
ATP-Team.

**Comment by at-huett** [comment]
#5
