### ISSUE TITLE
No display full option menu leave

### ISSUE THREAD

**Issue by at-nghiadt** [AsianTechInc/AT-Portal#7]
![bugpt](https://cloud.githubusercontent.com/assets/13099483/20333691/d2d828f2-abe6-11e6-91d2-2f6c7a130012.png)

**Comment by at-huett** [comment]
@at-nghiadt 
Cái này là do a bị sai Employee type, a đang ở Employee type là Collaborator nên không hiển thị đầy đủ menu leave, phải là Employee mới đầy đủ được. Cái này là issue data chứ ko phải bug nha a.
Thanks!

**Comment by at-nghiadt** [comment]
@at-huett 
Bug nhé Huệ
![bugpt1](https://cloud.githubusercontent.com/assets/13099483/20335345/74d78050-abf4-11e6-91ef-5c22cba63275.png)

**Comment by at-huett** [comment]
@at-nghiadt 
Employee type is Employee, includes: Staff and Probation . If it is Probation then only has 2 Leave type (Sick leave and Non-Paid). 
When I input your profile, I set Employee type is Probation, so we will edit your employee type.

Thank for contributing your opinions!
ATP-Team.

**Comment by at-huydq** [comment]
There is no Staff and Probation.
Only Employee and Employee On Probation.
Please use correct terms to avoid confusion in the future.
