### ISSUE TITLE
[Com_Timesheet] Display msg error when inputed information

### ISSUE THREAD

**Issue by at-linhntm** [AsianTechInc/AT-Portal#8]
Please check screenshot

**Screenshot**

![nh_ch p_man_hinh_111616_104625_am](https://cloud.githubusercontent.com/assets/13692674/20334071/eaa656ea-abe9-11e6-82fc-73bf6b10ea11.jpg)
![nh_ch p_man_hinh_111616_104708_am](https://cloud.githubusercontent.com/assets/13692674/20334082/04b12754-abea-11e6-9957-5fbb9481f233.jpg)

**Comment by at-datnm** [comment]
@at-linhntm 
Please explain your issue in detail

**Comment by at-linhntm** [comment]
i can't reproduce  this bug.

**Comment by at-datnm** [comment]
@at-linhntm 
Ok. I also don't see this issue reappears recently. This issue will be closed. Thank you!
